[package]
name = "gmta"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
cron = "0.12.1"
enigo = "0.2.1"
tokio = { version = "1.38.0", features = ["full"] }
tokio-macros = "2.3.0"
